---
# tasks file for daixijun.firewalld
- name: Install firewalld package
  yum:
    name: firewalld
    state: present
  when: not firewalld_disabled
  register: _firewalld_install_status

- name: Ensure iptables disabled
  systemd:
    name: iptables
    state: stopped
    enabled: false
  when:
    - ansible_virtualization_type != "docker"

- name: Ensure firewalld state
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - firewalld_disabled|bool
    - _firewalld_install_status is not skipped

- name: Add firewall rules if need
  firewalld:
    state: "{{ item.state | default(omit) }}"
    zone: "{{ item.zone | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    masquerade: "{{ item.service | default(omit) }}"
    immediate: "{{ item.immediate | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    permanent: "{{ item.permanent | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    rich_rule: "{{ item.rich_rule | default(omit) }}"
  loop: "{{ firewalld_rules }}"
  when:
    - not firewalld_disabled
    - firewalld_rules|lenght > 0
